### ISSUE TITLE
Missing release

### ISSUE THREAD

**Issue by Dinsen** [bitrise-io/codesigndoc#108]
Hi

I think you forgot to make a release of the latest version 2.3.1
I'm getting a 404 Not Found when I try to run an export.

```
$ bash -l -c "$(curl -sfL https://raw.githubusercontent.com/bitrise-tools/codesigndoc/master/_scripts/install_wrap.sh)"
 => Creating a temporary directory for codesigndoc ...
 => Downloading version: 2.3.1
 => Downloading codesigndoc from (https://github.com/bitrise-io/codesigndoc/releases/download/2.3.1/codesigndoc-Darwin-x86_64) to (/var/folders/6x/kqgh8k751gvc71nxxlmfrm4h0000gn/T/codesigndocXXXXXX.xMfHkBW1/codesigndoc) ...

curl: (22) The requested URL returned error: 404 Not Found
```

**Comment by mbrehme** [comment]
can confirm the missing release!

JFYI: Here is a workarround I used:
1. Create Shell Script using this content: https://raw.githubusercontent.com/bitrise-tools/codesigndoc/master/_scripts/install_wrap.sh
2. Change version_to_use to "2.3.0" => version_to_use="2.3.0"
3. run the script
4. enjoy ;-)

**Comment by bitce** [comment]
Hi guys! 

Thanks for all of your reports! We're looking into this and should be resolved shortly :)

**Comment by lpusok** [comment]
Hi all,
Sorry for the confusion. The release is now available. Will add checks to avoid this mistake in the future.

**Comment by lpusok** [comment]
Closing the issue.
