### ISSUE TITLE
Xcode 11 (Beta) issue to find certificates.

### ISSUE THREAD

**Issue by satoruokawa** [bitrise-io/codesigndoc#110]
Hi! I built a new app with Xcode 11, and wanted to set up a CI project with Bitrise.

My workspace could be archived manually through Xcode and through `xcodebuild` CLI, however, `codesigndoc` seemed that it couldn't find certificates.

```bash
$ bash -l -c "$(curl -sfL https://raw.githubusercontent.com/bitrise-tools/codesigndoc/master/_scripts/install_wrap.sh)"
 => Creating a temporary directory for codesigndoc ...
 => Downloading version: 2.3.1
 => Downloading codesigndoc from (https://github.com/bitrise-io/codesigndoc/releases/download/2.3.1/codesigndoc-Darwin-x86_64) to (/.../codesigndoc) ...
######################################################################## 100.0%
 => Making it executable ...
 => codesigndoc version: 2.3.1
 => Running codesigndoc scan ...

Scan the directory for project files
You can specify the Xcode project/workscape file to scan with the --file flag.
Found one project file: Project.xcworkspace.

🔦  Scanning Schemes ...
$ xcodebuild "-workspace" "/path/to/Project.xcworkspace" "-list"

Select the Scheme you usually use in Xcode
Please select from the list:
[1] : ...
[2] : ...
(type in the option's number, then hit Enter) [1] : 1

Xcode (xcodebuild) version: Xcode 11.0 (Build version 11M362v)


🔦  Running an Xcode Archive, to get all the required code signing settings...
$ xcodebuild "-workspace" "/path/to/Project.xcworkspace" "-scheme" "Project" "clean" "archive" "-archivePath" "/.../Project.xcarchive"
........................................................................................

💡  Saving xcodebuild output into file: /.../xcodebuild-output.log


🔦  Analyzing the archive, to get export code signing settings...
failed to analyze archive, error: installed certificate not found with common name or sha1 hash: Apple Development: Satoru Okawa (xxxx)
```

I checked if the certificate existed in my Keychain, and confirmed it did.
![Screen Shot 2019-07-16 at 2 57 57 PM](https://user-images.githubusercontent.com/8542019/61321850-5b6ba080-a7da-11e9-8e49-b517e8ebf3df.png)

I'm not sure why `codesigndoc` try to find a developer certificate, but I'd appreciate any advise! Thank you.

**Comment by bitce** [comment]
Hi @satoruokawa!

Thanks for your report! The codesigndoc tool isn't completely ready to support Xcode 11 quite yet, but we're working on it, so thanks for bringing it to our attention!

**Comment by satoruokawa** [comment]
Hi @bitce , thanks for your response! 

I manually exported the certificates by following your README, and it totally worked. Do I have to close this issue?

**Comment by stanfeldman** [comment]
Come on guys, can we get it working on Xcode 11 please?

**Comment by ThomasLeblond** [comment]
Hi @bitce, can you please give us some updates about this issue?

This PR (https://github.com/bitrise-io/codesigndoc/pull/112) is open since 12 days and we don't know if this fix the issue or not.

**Comment by sharpner** [comment]
The PR worked for me at least

**Comment by sregg** [comment]
I followed this doc and it worked fine: https://devcenter.bitrise.io/code-signing/ios-code-signing/exporting-code-signing-files/
Would be great to have a CLI working though...

**Comment by mkeremkeskin** [comment]
Is there any progress on this issue? I'm using manager profiles on my app and after adding new devices I need codesigndoc to uplaod my certificate.

**Comment by Dschee** [comment]
@sharpner How did you install the PR?

**Comment by tom-wolters** [comment]
Fix would be nice, thanks for your hard work guys!

**Comment by axelfran** [comment]
I agree. Hope to see a fix soon :)

**Comment by ThomasLeblond** [comment]
![Alt Text](https://media.giphy.com/media/4NnTap3gOhhlik1YEw/giphy.gif)

**Comment by ThomasLeblond** [comment]
<img src="https://media.giphy.com/media/4NnTap3gOhhlik1YEw/giphy.gif" width="40" height="40" />

**Comment by ThomasLeblond** [comment]
![Alt Text](https://media.giphy.com/media/tXL4FHPSnVJ0A/giphy.gif)

**Comment by godrei** [comment]
Hi @satoruokawa and every contributor, thanks for the issue reports. We released a [new version of codesigndoc](https://github.com/bitrise-io/codesigndoc/releases/tag/2.4.0). Pls try it and let us know if it does not work well with Xcode 11 in a new Issue thread.
