### ISSUE TITLE
Codesign fails with XCode 12 if project has Swift Package with min deployment target of 8

### ISSUE THREAD

**Issue by valentary** [bitrise-io/codesigndoc#127]
I'm using the Oauth2 Package from https://github.com/p2/OAuth2
The archive builds on it's own through XCode (I uploaded to testflight yesterday)

Here is the output:
Xcode (xcodebuild) version: Xcode 12.0.1 (Build version 12A7300)

🔦  Running an Xcode Archive, to get all the required code signing settings...
$ xcodebuild "-workspace" “/<redacted>.xcworkspace" "-scheme" “<>redacted” "clean" "archive" "-archivePath" "/var/folders/3s/mdztfg4s55dcq44x1gx33hxm0000gq/T/__codesigndoc__809391677/<redacted>.xcarchive"
.................................................................

Last lines of the build log:
warning: The iOS deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 14.0.99. (in target 'OAuth2' from project 'OAuth2')
warning: The iOS deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 14.0.99. (in target 'SwiftKeychain' from project 'OAuth2')
warning: The iOS deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 14.0.99. (in target 'Base' from project 'OAuth2')
warning: The iOS deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 14.0.99. (in target 'iOS' from project 'OAuth2')
warning: The iOS deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 14.0.99. (in target 'macOS' from project 'OAuth2')
warning: The iOS deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 14.0.99. (in target 'tvOS' from project 'OAuth2')
warning: The iOS deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 14.0.99. (in target 'Flows' from project 'OAuth2')
warning: The iOS deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 14.0.99. (in target 'DataLoader' from project 'OAuth2')
warning: The iOS deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 14.0.99. (in target 'OAuth2' from project 'OAuth2')
** ARCHIVE FAILED **

The following build commands failed:
	PhaseScriptExecution [CP]\ Check\ Pods\ Manifest.lock /<redacted>/Library/Developer/Xcode/DerivedData/<redacted>evbvduhcsylvdwfdmamwdvshrpew/Build/Intermediates.noindex/ArchiveIntermediates/<redacted>/IntermediateBuildFilesPath/<redacted>.build/Release-iphoneos/<redacted>.build/Script-7BCBF2A4071613CD8E5918CC.sh
(1 failure)
Please check the build log to see what caused the error.

Xcode Archive failed.
Open the project: <redacted>.xcworkspace
and make sure that you can build an Archive, with the scheme: <redacted>

💡  Saving xcodebuild output into file: <redacted>/codesigndoc_exports/xcodebuild-output.log

------------------------------
First of all please make sure that you can Archive your app from Xcode.
codesigndoc only works if you can archive your app from Xcode.
If you can, and you get a valid .ipa/.app file if you export from Xcode,
please create an issue on GitHub at: https://github.com/bitrise-io/codesigndoc/issues
with as many details & logs as you can share!
------------------------------

Error: failed to run xcodebuild command, error: exit status 65

**Comment by mjones-droid** [comment]
Hey @valentary!

Could you send me a build where this was happening? Also, please [enable support access for the app](https://devcenter.bitrise.io/troubleshooting/enabling-bitrise-support-user/).

Matthew
Senior Customer Engineer

**Comment by valentary** [comment]
Hello,

This isn't happening on a build in bitrise, just locally, when I'm trying to upload a new profile to bitrise

**Comment by mjones-droid** [comment]
My apologies. I understand what's happening now. You're trying to use the codesigndoc tool to upload your certificates and codesigning profiles to Bitrise. When the codesigndoc runs the first thing it does is perform an Xcode archive. For some reason that archive failed. 

Unfortunately the terminal output you posted isn't enough to determine the cause of the failure. You'd have to look in the Xcode build log, which codesigndoc placed in /codesigndoc_exports/xcodebuild-output.log.

Please grab that log and post the error found there. Thanks!

Matthew
Senior Customer Engineer

**Comment by valentary** [comment]
This got put on a backburner for a little bit.
I found the problem, one of our cocoapods wasn't working with xcode 12.2 and so I'd installed an earlier version, but had not specified the correct command line tools, so the script was still using 12.2, and so had the same problem I did. 
Once I set the correct command line tool, it worked again.
Thanks!
