### ISSUE TITLE
Add "destination" flag for Xcode scans. 

### ISSUE THREAD

**Issue by jhmacdon** [bitrise-io/codesigndoc#129]
Currently this fails for me:
`xcodebuild -scheme <myScheme> archive -sdk iphoneos`

With the error:
`error: unable to resolve product type 'com.apple.product-type.application.watchapp2' for platform 'iphoneos' (in target 'WatchApp' from project 'myProject')`

I was, however, able to get this working by specifying a destination:
`xcodebuild -scheme <myScheme> archive -destination="iphoneOS,iPhone 11"`

Would love if I could add a destination flag (or, even more future proof, a way to specify any args to pass to the `xcodebuild` command

**Comment by Roland-Bak** [comment]
Hello @jhmacdon 👋

I have forwarded your request to our Product Team for consideration regarding future features, but in the meantime you could also post this in our Forums, under Feature Request, as the more widespread demand for a feature, the more likely it will move up in priority.

You can create a request here: [(https://discuss.bitrise.io/c/feature-request)]

Hope this helps!

**Comment by jackdewhurst** [comment]
Adding this ability would fix https://github.com/bitrise-io/codesigndoc/issues/131 too.

**Comment by shams-ahmed** [comment]
Release 2.4.4 resolves issues with M1 as well as adds additional options for -sdk and -destination :
-sdk: If a value is specified for this flag it'll be passed to xcodebuild as the value of the -sdk flag. For more info about the values please see xcodebuild's -sdk flag docs. Example value: iphoneos")

-destination: The xcodebuild -destination option takes as its argument a destination specifier describing the device (or devices) to use as a destination i.e generic/platform=iOS.
