### ISSUE TITLE
codesigndoc error when build

### ISSUE THREAD

**Issue by funcsatish** [bitrise-io/codesigndoc#91]
_Please include the full (Terminal) output of `codesigndoc` -
in Terminal.app you can save the output into a file with `Command+s`_

_In addition to this, if `codesigndoc` generated an Xcode output log, please attach that too._

➜  codesigndoc go build
# codesigndoc/vendor/github.com/bitrise-tools/codesigndoc/osxkeychain
ld: warning: text-based stub file /System/Library/Frameworks//Security.framework/Security.tbd and library file /System/Library/Frameworks//Security.framework/Security are out of sync. Falling back to library file for linking.
# codesigndoc/vendor/github.com/bitrise-tools/codesigndoc/osxkeychain
vendor/github.com/bitrise-tools/codesigndoc/osxkeychain/osxkeychain.go:179:49: cannot use nil as type _Ctype_CFAllocatorRef in argument to _Cfunc_CFDictionaryCreateMutable

**Comment by bitce** [comment]
Hi there! 

Sorry about the very late reply here, could you please include the full terminal output of the instance you are attempting to run codesigndoc? 

Also, you may contact us about this on our on-site chat for faster resolution!

**Comment by ios3** [comment]
# codesigndoc/vendor/github.com/bitrise-tools/codesigndoc/osxkeychain
ld: warning: text-based stub file /System/Library/Frameworks//Security.framework/Security.tbd and library file /System/Library/Frameworks//Security.framework/Security are out of sync. Falling back to library file for linking.
# codesigndoc/vendor/github.com/bitrise-tools/codesigndoc/osxkeychain
vendor/github.com/bitrise-tools/codesigndoc/osxkeychain/osxkeychain.go:179:49: cannot use nil as type _Ctype_CFAllocatorRef in argument to _Cfunc_CFDictionaryCreateMutable
